apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-application
  labels:
    app: lab-application
    tier: api
spec:
  replicas: 2
  template:
    metadata:
      name: lab-application-pod
      labels:
        app: lab-application
    spec:
      containers:
        - name: lab-application
          image: xuthyst/lab-application:latest
  selector:
    matchLabels:
        app: lab-application