apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-application-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab-application
  template:
    metadata:
      labels:
        app: lab-application
    spec:
      containers:
      - name: lab-application
        image: docker.io/xuthyst/sre-acad-module2:latest
        ports:
        - containerPort: 5000
