apiVersion: v1
kind: Service
metadata:
  name: lab-application-service
spec:
  selector:
    app: lab-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
